language: java
jdk:
  - oraclejdk8

git:
  submodules: false
  depth: 1

before_install:
  - openssl aes-256-cbc -K $encrypted_70c31ee585ad_key -iv $encrypted_70c31ee585ad_iv -in bin/anychart-deploy-key.enc -out bin/anychart-deploy-key -d
  - chmod 600 bin/anychart-deploy-key
  - cp bin/anychart-deploy-key ~/.ssh/id_rsa
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

install:
  - git submodule update --init
  - pip install maxcdn --user
  - ./build.py libs

script:
  - echo -e "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" >> ~/.npmrc
  - echo -e "Host $STATIC_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git rev-parse HEAD >> ./dist/commit-hash.txt
  - ./bin/make_build.sh


after_success:
  - curl -X POST $TESTS_HOST/ci_test --data "branch=$TRAVIS_BRANCH&commit=$TRAVIS_COMMIT"
